// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rcmbmmuonnjrqfzascsc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJjbWJtbXVvbm5qcnFmemFzY3NjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNDIyOTcsImV4cCI6MjA2MzgxODI5N30.ZjhaKP2k-CX9XS_qiozpAcNqQ52ogPBZAr6P1ZwktwM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);